### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [zixun/NetworkEye#1]
Hi,
For iOS and macOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://bit.ly/2IWvGks)
- [Carthage Tutorial: Getting Started](https://bit.ly/2zes4dN)
- [Making Carthage-compatible Frameworks with Swift](https://bit.ly/2tXUofp)
- [Swift Cross Platform Framework](https://bit.ly/2ysgETA) (section [Configure targets for Carthage](https://bit.ly/2tZUOSt)) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by zixun** [comment]
Thanks for your articles， I will support it as soon as possible~

**Comment by zixun** [comment]
@TofPlay  I have make a new branch named [carthage](https://github.com/zixun/NetworkEye/tree/carthage) to do it. but I have some problems to work, the shared `Network` target can‘t be build. it can't find the dependency `AppSwizzle`.

and I had add the `AppSwizzle.framework` to the `Link Binary With Libraries`, and add the `Run Script`.

could you help me to find the problems in it, I'm not familiar with `Carthage`,thank you!

**Comment by zixun** [comment]
I have found the reason. same as 
[also need to set the Framework Search Paths](https://github.com/Carthage/Carthage/issues/956)
